language: node_js

node_js:
  - node

services:
  - docker

before_install:
 - docker pull node:14-alpine

script:
 - docker run -it -p 3000:3000 --mount type=bind,source=$(pwd),target=/app -w=/app  node:14-alpine npm run test


