version: '2'
services:
  node:
    image: "node:14-alpine"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "npm run start"
    environment:
            URL: http://myurl:123
